### ISSUE TITLE
failed to build the dockerfile

### ISSUE THREAD

**Issue by 7oud** [NIST-MNI/nist_mni_pipelines#16]
it is not easy to setup the enviroment of building average model, I tried to build the dockerfile in `container` folder, but there were some mistakes as follow
```bash
[+] Building 0.5s (17/17) FINISHED                                                                                                       docker:default
 => [internal] load build definition from Dockerfile                                                                                               0.0s
 => => transferring dockerfile: 3.39kB                                                                                                             0.0s
 => [internal] load metadata for ghcr.io/mamba-org/micromamba:1.5.6-focal                                                                          0.4s
 => [internal] load .dockerignore                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                    0.0s
 => [internal] load build context                                                                                                                  0.0s
 => => transferring context: 65B                                                                                                                   0.0s
 => [builder 1/7] FROM ghcr.io/mamba-org/micromamba:1.5.6-focal@sha256:a5c5886b028fb0c74f2b9564efee6d34ab5291fe158dff5659b75e1c20d26974            0.0s
 => => resolve ghcr.io/mamba-org/micromamba:1.5.6-focal@sha256:a5c5886b028fb0c74f2b9564efee6d34ab5291fe158dff5659b75e1c20d26974                    0.0s
 => CACHED [builder 2/7] COPY --chown=mambauser:mambauser env.yaml /tmp/env.yaml                                                                   0.0s
 => CACHED [builder 3/7] RUN --mount=type=cache,target=/opt/conda/pkgs     micromamba install -y -n base -f /tmp/env.yaml                          0.0s
 => CACHED [builder 4/7] RUN mkdir /opt/pipeline  &&     chown mambauser:mambauser -R /opt/pipeline                                                0.0s
 => ERROR [builder 5/7] COPY --chown=mambauser:mambauser nist_mni_pipelines.tar.gz /tmp/nist_mni_pipelines.tar.gz                                  0.0s
 => CACHED [builder 6/7] RUN tar -xzvf /tmp/nist_mni_pipelines.tar.gz -C /opt/pipeline --strip-components=1                                        0.0s
 => CACHED [builder 7/7] COPY --chown=mambauser:mambauser run_pipeline.sh /opt/pipeline/                                                           0.0s
 => CACHED [stage-1 2/7] COPY --from=builder /opt/conda    /opt/conda                                                                              0.0s
 => CACHED [stage-1 3/7] COPY --from=builder /opt/pipeline /opt/pipeline                                                                           0.0s
 => CACHED [stage-1 4/7] COPY --chown=mambauser:mambauser models/icbm152_model_09c   /opt/models/icbm152_model_09c                                 0.0s
 => CACHED [stage-1 5/7] COPY --chown=mambauser:mambauser models/ipl_bison_1.3.0     /opt/models/ipl_bison_1.3.0                                   0.0s
 => CACHED [stage-1 6/7] COPY --chown=mambauser:mambauser models/wmh_bison_1.3.0     /opt/models/wmh_bison_1.3.0                                   0.0s
 => ERROR [stage-1 7/7] COPY --chown=mambauser:mambauser models/synthstrip          /opt/models/synthstrip                                         0.0s
------
 > [builder 5/7] COPY --chown=mambauser:mambauser nist_mni_pipelines.tar.gz /tmp/nist_mni_pipelines.tar.gz:
------
------
 > [stage-1 7/7] COPY --chown=mambauser:mambauser models/synthstrip          /opt/models/synthstrip:
------
Dockerfile:53
--------------------
  51 |     COPY --chown=$MAMBA_USER:$MAMBA_USER models/ipl_bison_1.3.0     /opt/models/ipl_bison_1.3.0
  52 |     COPY --chown=$MAMBA_USER:$MAMBA_USER models/wmh_bison_1.3.0     /opt/models/wmh_bison_1.3.0
  53 | >>> COPY --chown=$MAMBA_USER:$MAMBA_USER models/synthstrip          /opt/models/synthstrip
  54 |
  55 |
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 7C2U:BRCD:2D4P:5BXS:ZWVH:CAGJ:QEOC:BTVX:K2DA:CPI3:Q5PH:HHOS::4f1tknsjr9tee4sulmcfaojo0: "/models/synthstrip": not found
```
Should I download the model file into some specific position in advance? I noticed that some commetted lines in dockerfile, should I uncomment them? If there is a docker on docker hub, that will be the BEST! Looking forward to your answers.

**Comment by vfonov** [comment]
I made an apptainer/singularity container for now ( https://github.com/NIST-MNI/nist_mni_pipelines/blob/modernize/container/nist_pipeline_0.2.00.beta.def ) but it relies on local archive of files. I tried to make it available via github packages at `oras://ghcr.io/nist-mni/nist_mni_pipelines:0.2.00`

**Comment by vfonov** [comment]
so, i update the docker image. It is available at https://hub.docker.com/repository/docker/nistmni/nist_mni_pipeline/general 

to run it , see an example in https://github.com/NIST-MNI/nist_mni_pipelines/blob/modernize/validation/run_validation_docker.sh

**Comment by 7oud** [comment]
**wonderful!!!** I download the `ipl_subject43.tar.gz` and unzip it. modify `nist_mni_pipeline:0.2.00` to `nistmni/nist_mni_pipeline` in `run_validation_docker.sh`, then I ran the script.
Here's the outputs,
```bash
+ FIELD=1.5
+ PRL=4
+ THREADS=4
+ out=output_docker
+ CLEANUP=YES
+ cat -
######################################################################
# Running validation dataset using apptainer, results will be in output_docker directory
#
#
# Using parameters for 1.5T scanner, 4 parallel processes, maximum 4 threads
#
#######################################################################
+ mkdir -p output_docker
++ pwd
++ id -u
++ id -g
+ docker run --rm --shm-size=10gb -v /home/zoud/workspace/github/samples/nist_mni_pipelines/validation:/data -w /data --user 1000:1000 --env PRL,THREADS=4,RAY_memory_monitor_refresh_ms=0,CLEANUP=YES nistmni/nist_mni_pipeline:0.2.00 --csv subject43.csv --out output_docker
2024-07-02 08:39:23,005 INFO worker.py:1673 -- Started a local Ray instance.
Traceback (most recent call last):
  File "/opt/pipeline/ipl_longitudinal_pipeline.py", line 9, in <module>
    main()
  File "/opt/pipeline/ipl/cli/longitudinal_pipeline.py", line 717, in main
    launchPipeline(opts)
  File "/opt/pipeline/ipl/cli/longitudinal_pipeline.py", line 239, in launchPipeline
    assert 'subject' in df.columns, "csv file should contain a list of patients with 'subject' column"
AssertionError: csv file should contain a list of patients with 'subject' column
```
and here is the files
```bash
.
├── download_validation_dataset.sh
├── ipl_subject43.tar.gz
├── output_docker
├── run_validation_apptainer.sh
├── run_validation_direct_list.sh
├── run_validation_docker.sh
├── subject43
│   ├── subject43_1_pdw.mnc
│   ├── subject43_1_t1w.mnc
│   ├── subject43_1_t2w.mnc
│   ├── subject43_2_pdw.mnc
│   ├── subject43_2_t1w.mnc
│   ├── subject43_2_t2w.mnc
│   ├── subject43_3_pdw.mnc
│   ├── subject43_3_t1w.mnc
│   ├── subject43_3_t2w.mnc
│   ├── subject43_4_pdw.mnc
│   ├── subject43_4_t1w.mnc
│   └── subject43_4_t2w.mnc
└── subject43.csv

```
Are there any other files have to be downloaded in advance?

**Comment by vfonov** [comment]
Add the header line `subject,visit,t1w,t2w,pdw,age,sex`  to the subject43.csv ,I forgot to update the `ipl_subject43.tar.gz` archive.

**Comment by 7oud** [comment]
**GREAT!!!** Now the docker container runs and outputs files in `output_docker` folder correctly.
and I run the container in an interactive way to understand file structure and calling order of the code
```bash
docker run -it --rm --entrypoint /bin/bash nistmni/nist_mni_pipeline:0.2.00
```

My aim is to learn the average template creating method to make a CT atlas for brain, which may be not so complicate as the method in this repo. Since I don't care about `age-appropriate` or `specific subject`. So, could you some advices to learn the basic method of altas construction in this repo, e.g. some params to run the script to create a vanilla atlas or the main funcs about createing a vanilla atlas

**Comment by vfonov** [comment]
did you read the paper? https://doi.org/10.1016/j.neuroimage.2010.07.033 

The method is implemented in https://github.com/NIST-MNI/nist_mni_pipelines/blob/modernize/ipl/model/generate_nonlinear.py , no need to dig inside the docker container.
